### ISSUE TITLE
formulär för parkering

### ISSUE THREAD

**Issue by NinaRomanus** [drlindh/www#30]
Snyggt formulär :-)
Det ska skickas till Jenny på revisrosringen (det jag vet nu i alla falla)
jenny.bergendahl@revisorsringen.se

på många av raderan är det ett understräck (_) för kolontecknet. Det är nog inte meningen. Jag ser inte hur jag ska kunna ta bort det.

**Comment by mberglundmx** [comment]
Åtgärdat - Jenny behöver sannolikt godkänna att ta emot mailen, men jag vbf:ar tills hon bekräftat att hon får dem.
